### PR TITLE
Update dmgbuild to 1.2.1

### LINKED ISSUE #1: dmgbuild is out of date
dmgbuild is now version 1.2.1, which introduces support for macOS Sierra.

I was just going to update myself in a fork but I realize that you did some generation here and it may be easier for you to do it if you still have that set up. Let me know otherwise.

### PR DESCRIPTION
**Pull request by panathea**
Fix #1 

I've updated dmgbuild and two dependencies to bring this formula up to date.

Only tested locally on my own machine.

### CODE REVIEW

**Comment by seanfisk** [comment]
Thank you! Sorry it's taken me so long to get to this. I'm investigating the Travis failure right now; shouldn't take too long. I don't believe it's related to your changes.

**Comment by panathea** [comment]
No problem at all.

This is a little off topic, but in an attempt to get off Homebrew, I built a dmgbuild pex which works with the built-in Apple Python: https://github.com/morinted/dmgbuild/releases

Maybe it could help you too.

**Comment by seanfisk** [comment]
I hadn't heard of pex — it looks pretty cool!

The reason I [originally created this tap](https://bitbucket.org/al45tair/dmgbuild/pull-requests/10/add-installation-document-and-homebrew-tap/diff) is because I wanted to use dmgbuild for projects that used Python 3 (dmgbuild only supported Python 2) and non-Python projects. So needing a separate Python environment is a bit of a hassle, especially for non-Python devs. However, dmgbuild's author [rejected my pull request](https://bitbucket.org/al45tair/dmgbuild/pull-requests/10/add-installation-document-and-homebrew-tap/activity) which was kind of frustrating.

I think that pex may be able to solve this problem, and I also considered re-writing dmgbuild in another language that would make it easier to release as a standalone tool (e.g., Swift).

Anyway, I fixed Travis and your PR looks good. Thanks so much for the contribution!

**Comment by panathea** [comment]
Yeah, that's fair. I have the same use case: python3 project just using dmgbuild, and the pex does accomplish that as well. I appreciated finding this repo!

**Comment by seanfisk** [comment]
Thanks for exposing me to pex and for the pull request!

**Pull request merged**
